STATUS_CODE_OK = 200
STATUS_CODE_CREATED = 201
STATUS_CODE_BAD_REQUEST = 400
STATUS_CODE_UNAUTH = 401
STATUS_CODE_NOT_FOUND = 404
STATUS_CODE_NO_METHOD = 405
STATUS_CODE_UNPROCESSABLE = 422
STATUS_CODE_SERVER_ERROR = 500

CONTENT_TYPE_JSON = 'application/json; charset=utf-8'
